services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube-container
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres-service:5432/sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - net-sonar
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  postgres-service:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net-sonar
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sonar"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  sonarqube_data: {}
  sonarqube_extensions: {}
  sonarqube_logs: {}
  postgres_data: {}

networks:
  net-sonar:
    driver: bridge
